### ISSUE TITLE
Parallel = True is causing unnecessary errors

### ISSUE THREAD

**Issue by shivangk** [unbiasedmodeler/pycausalmatch#1]
When you put _`parallel = True`_ then the block computing all the distances doesn't get executed and you get an error as `shortest_distance_df` is not created but getting called in the block below. Ideally we should not keep this argument in current version till we have parallel execution in place.

![image](https://user-images.githubusercontent.com/7772139/114850615-99a65180-9dfe-11eb-9fd0-38fb01fb0b35.png)

**Comment by rj678** [comment]
Thank you for this suggestion @shivangk  - this library is still a WIP. I did an alpha release for a project with a colleague. I will make this clear in the README and hopefully get around to your suggestions and the numerous other bugs soon 🤞 

thanks again!

**Comment by rj678** [comment]
Thanks for pointing this out @shivangk - I have fixed the error that was being thrown in v0.0.2. The code executes sequentially even if `parallel=True` for now, with a warning - I will add parallel execution soon.
