### ISSUE TITLE
appending to a dataframe needs to be assigned to itself

### ISSUE THREAD

**Issue by shivangk** [unbiasedmodeler/pycausalmatch#2]
While appending we will need to assign the dataframe back to itself otherwise now what is happening we are getting only first market matched output rest all are getting lost. _Don't focus on the print command, that's I have written while searching for a reason of loss of my data._

![image](https://user-images.githubusercontent.com/7772139/114851143-205b2e80-9dff-11eb-9178-0837199f7f0f.png)

**Comment by rj678** [comment]
Thank you for this suggestion @shivangk  - this library is still a WIP. I did an alpha release for a project with a colleague. I will make this clear in the README and hopefully get around to your suggestions and the numerous other bugs soon 🤞 

thanks again!

**Comment by rj678** [comment]
Thanks for pointing this out @shivangk - I have fixed this bug! I have also added a note on the README that I have only tested the code for a single Test market - I will test this on multiple test markets soon.
