### ISSUE TITLE
Save Graph

### ISSUE THREAD

**Issue by dariocorral** [unbiasedmodeler/pycausalmatch#5]
Hi,

First of all thanks for sharing this project. It's very useful

I know that it seems a stupid question but I don't know how can I save your plots like this one from your notebook example.

`results_only_cph['all_output_plots'](figsize=(14,16))

Thanks

**Comment by rj678** [comment]
thanks for your definitely-not-stupid question @dariocorral , I expose the underlying Causal Impact object with the results,  which is available at `results_only_cph['causal_impact_object']` , and someone was kind enough to add a kwarg  `show` to give access to the figure so it could be saved (see this PR: https://github.com/WillianFuks/tfcausalimpact/pull/13)

can you try this to save the figure:

```
import matplotlib.pyplot as plt
results_only_cph['causal_impact_object'].plot(show=False)
fig = plt.gcf()
fig.savefig("causal_results.png")
```

please let me know if this does not help

**Comment by dariocorral** [comment]
Hi @rishi1016 ,

Thanks a lot but it's not working properly when I try to save fig. It says that there is not "show" method available.

Regards.
